prefix = 'https://www.warrennolan.com/basketball/2023/team-net-sheet?team='
teamUrls = [prefix+'Alabama', prefix+'Kansas', prefix+'Houston', prefix+'Purdue',
            prefix+'UCLA', prefix+'Texas', prefix+'Baylor', prefix+'Arizona',
            prefix+'Marquette', prefix+'Kansas-State', prefix+'Gonzaga', prefix+'Tennessee',
            prefix+'Connecticut', prefix+'Xavier', prefix+'Indiana', prefix+'Virginia',
            prefix+'Miami-FL', prefix+'Saint-Marys-College', prefix+'San-Diego-State', prefix+'Iowa-State',
            prefix+'TCU', prefix+'Creighton', prefix+'Kentucky', prefix+'Texas-AM',
            prefix+'Duke', prefix+'Michigan-State', prefix+'Northwestern', prefix+'Missouri',
            prefix+'Iowa', prefix+'Maryland', prefix+'Illinois', prefix+'FAU',
            prefix+'Arkansas', prefix+'West-Virginia', prefix+'Auburn', prefix+'Memphis',
            prefix+'Boise-State', prefix+'Providence', prefix+'USC', prefix+'North-Carolina-State',
            prefix+'Pittsburgh', prefix+'Rutgers', prefix+'Utah-State', prefix+'Mississippi-State',
            prefix+'Nevada', prefix+'Penn-State', prefix+'Wisconsin', prefix+'Arizona-State',
            prefix+'Oklahoma-State', prefix+'Michigan', prefix+'Clemson', prefix+'North-Carolina',
            prefix+'Charleston', prefix+'Oral-Roberts', prefix+'Drake', prefix+'VCU',
            prefix+'Toledo', prefix+'Utah-Valley', prefix+'Iona', prefix+'Yale',
            prefix+'Louisiana', prefix+'UC-Irvine', prefix+'Furman', prefix+'Kennesaw-State',
            prefix+'Colgate', prefix+'Montana-State', prefix+'Vermont', prefix+'UNC-Asheville',
            prefix+'Northern-Kentucky', prefix+'Fairleigh-Dickinson', prefix+'Southeast-Missouri', prefix+'Texas-AM-Corpus-Christi', 
            prefix+'Howard', prefix+'Grambling-State']

