prefix = 'https://www.warrennolan.com/basketball/2026/team-net-sheet?team='
teamUrls = [prefix+'Duke', prefix+'Michigan', prefix+'Arizona', prefix+'Florida',
            prefix+'Connecticut', prefix+'Houston', prefix+'Illinois', prefix+'Michigan-State',
            prefix+'Iowa-State', prefix+'Nebraska', prefix+'Gonzaga', prefix+'Purdue',
            prefix+'Alabama', prefix+'Virginia', prefix+'Kansas', prefix+'Texas-Tech',
            prefix+'Vanderbilt', prefix+'Arkansas', prefix+'Saint-Johns', prefix+'North-Carolina',
            prefix+'Tennessee', prefix+'Wisconsin', prefix+'Louisville', prefix+'BYU',
            prefix+'Kentucky', prefix+'Miami-FL', prefix+'Saint-Marys-College', prefix+'Villanova',
            prefix+'Georgia', prefix+'UCLA', prefix+'Clemson', prefix+'Utah-State',
            prefix+'TCU', prefix+'Iowa', prefix+'Ohio-State', prefix+'Saint-Louis',
            prefix+'Texas-AM', prefix+'UCF', prefix+'North-Carolina-State', prefix+'Miami-OH',
            prefix+'Missouri', prefix+'Santa-Clara', prefix+'Texas', prefix+'SMU',
            prefix+'VCU', prefix+'Oklahoma', prefix+'Auburn', prefix+'Indiana',
            prefix+'New-Mexico', prefix+'San-Diego-State', prefix+'Boise-State', prefix+'Cincinnati',
            prefix+'Virginia-Tech', prefix+'Stanford', prefix+'Seton-Hall', prefix+'South-Florida',
            prefix+'Akron', prefix+'Yale', prefix+'Mcneese', prefix+'High-Point', 
            prefix+'Northern-Iowa', prefix+'Utah-Valley', prefix+'Hofstra',
            prefix+'UC-Irvine', prefix+'North-Dakota-State', prefix+'Troy', prefix+'Wright-State',
            prefix+'Tennessee-State', prefix+'Furman', prefix+'Idaho', prefix+'Siena',
            prefix+'Queens', prefix+'UMBC', prefix+'Long-Island', prefix+'Howard', 
            prefix+'Lehigh', prefix+'Penn', prefix+'Dayton',
            prefix+'Wichita-State',prefix+'Prairie-View-AM', prefix+'Kennesaw-State',
            prefix+'Hawaii', prefix+'California-Baptist']
